### PR TITLE
Issues/38b

### PR DESCRIPTION
**Pull request by pmlopes**
Motivation:

This is a remake of #39 because the rebase turned out to be too complex.

### CODE REVIEW

**Comment by pmlopes** [comment]
Fixes #38 and #39

**Comment by pmlopes** [comment]
@slinkydeveloper the core functionality is on the 1st commit: https://github.com/eclipse-vertx/vertx-json-schema/pull/40/commits/2bfb5e2be90a828c8b7710042d4e03e4a166976a

The second one is just linting fixes, adding missing static/final, removing unused imports, enhanced forloops and simplified streaming calls.

**Review by slinkydeveloper — COMMENTED** [review]
I left a comment. Except that, I think we're good to go

**Comment by pmlopes** [comment]
I can't do that. There's a reason for the 2 lines:

```java
// in this line I keep a reference to the "source" object that was passed to the validation method
// the reason is that we may mutate the "in" reference when unwrapping
// by mutating it it means that recursive calls or logs would see the unwrapped value instead,
// so keeping it here allows me to keep the same logging/processing no matter if wrapping happened or not
final Object orig = in;
```

The second line:

```java
// this line may or may not change in input object reference
// is most cases it's just an identity function but for json types it unwraps them to java.util.Map/List
// this way we only deal with these primitives internally
in = unwrap(in);
```

**Comment by pmlopes** [comment]
@slinkydeveloper I can however invert the variable names to reduce that style, for example:

```java
// note that i tag the last arg as final and name it "orig" now
public void validateSync(ValidatorContext context, final Object orig) throws ValidationException {
  Object in = unwrap(orig);
  // from here all the same as before
...
```

This way it may be more readable? WDYT?

**Comment by slinkydeveloper** [comment]
> This way it may be more readable? WDYT?

Yep definitely, go for it!

**Review by slinkydeveloper — APPROVED** [review]

**Comment by slinkydeveloper** [comment]
Thanks for the contribution!

**Pull request merged**
