### PR TITLE
Adding idn-hostname support and some additional TCK coverages

### PR DESCRIPTION
**Pull request by CheesyBoy123**
Motivation:

As a part of https://github.com/eclipse-vertx/vertx-json-schema/issues/81 I am addressing some unsupported tests. I added support for idn-hostname format checking, and a small fix for ipv4 TCK testcase.

idn-hostname is not completely done, but it is passing more than half the TCs now. Please let me know your thoughts on this.

Conformance:

You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by pk-work** [comment]
Hi, normally I would merge the PR directly, but there were also some test cases which got disabled now. This would mean the functionality has changed.

Is it possible that all test cases that were previously supported will continue to be supported?

**Comment by CheesyBoy123** [comment]
Hey @pk-work I've updated the PR and added a new check for the Virma character to fix the TCs I added to the "unsupported" list.
The only things i've added are the "annotation" only tests, hopefully we are good now for this change!

**Comment by pk-work** [comment]
Hi @CheesyBoy123 now it looks good! Thank you very much!

To be honest I had some headache to understand the meaning of these annotation only test cases. My current interpretation is that it's the same category as the other tests around it like "all string formats ignore booleans". So this means if we have a String that starts with (or even contains?) a character that's not allowed in idn hostnames, this format should be ignored.

It seems that the first character "〮" is somehow "invalid", but I don't know why. Because it is a valid unicode 5.1 character. But when I use this tool [1], I can't convert "〮실례.테스트" into a ACE String. But "실례.테스트" can be converted into "xn--9n2bp8q.xn--9t4b11yi5a.de"

Before I merge this commit, I'd like to understand the reason / impact for this and then we can decide if we can skip the test or not.

Do you know what happens here? I will also ask some colleagues.

[1] https://www.denic.de/service/tools/idn-web-converter#idnace-form

**Comment by CheesyBoy123** [comment]
Hey @pk-work from my understanding on what "annotation only" means by looking at other TCK tests is that in these specs even if the field is invalid for this case, we shouldn't fail the validation we should only annotate. These tests are kinda confusing considering they come in pairs:

https://github.com/eclipse-vertx/vertx-json-schema/blob/master/src/test/resources/test-suite-tck.json#L7265 
https://github.com/eclipse-vertx/vertx-json-schema/blob/master/src/test/resources/test-suite-tck.json#L17791

In the annotate test valid is true because we should only annotate, but in the optional format test it should fail... So I think adding the annotate tests to the unsupported tests file should be ok.

As for why "〮실례.테스트" is invalid, the idn hostname cannot contain the unicode character "\\u302e". 

Also similar "annotation" tests that are already in the properties file such as email:
https://github.com/eclipse-vertx/vertx-json-schema/blob/master/src/test/resources/test-suite-tck.json#L3013
https://github.com/eclipse-vertx/vertx-json-schema/blob/master/src/test/resources/test-suite-tck.json#L7098

Hopefully this helps clear things up! Thanks! 😄

**Comment by pk-work** [comment]
@CheesyBoy123 Thank you very much for your detailed answer. This was very helpful.

**Review by pk-work — APPROVED** [review]

**Pull request merged**
