### PR TITLE
Implement exact arithmetic for 'multipleOf' validation

### PR DESCRIPTION
**Pull request by afloarea**
Signed-off-by: Adrian Floarea <adrianfloarea07@yahoo.com>

Motivation:

Implement exact arithmetic for 'multipleOf' validation. See https://github.com/vert-x3/vertx-web/issues/2105

### CODE REVIEW

**Comment by pmlopes** [comment]
@afloarea I've backported the fix we already had in order to get the latest TCK to pass. It is slightly different from your PR. While your PR is always converting numbers to string to big decimal, the alternative is trying to only do that conversion when we're dealing with floating point numbers and going back to integer math for the remaining cases.

**Comment by afloarea** [comment]
I didn't know you had fixed it already. In any case, thank you for resolving the issue. :)

**Comment by gjovicic** [comment]
What is with this? Why is this fix not in current vert.x version?

**Comment by pk-work** [comment]
What makes you think, it isn't in?

**Comment by gjovicic** [comment]
When I go to that class https://github.com/eclipse-vertx/vertx-json-schema/blob/4.4/src/main/java/io/vertx/json/schema/common/MultipleOfValidatorFactory.java on 4.4 version, I see double is still used.

**Pull request closed without merging**
